# Basic
title: Modrisco
subtitle: Joseph Meng's personal blog
description: Information Technology student graduated from BUPT and now learning in UNSW.
creator: <a href="http://github.com/Modrisco">@Modrisco</a>

url: "http://mlx7.xyz"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About me, description: About me, url: 'http://linkedin.com/in/menglingxu'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: www-mlx7-xyz
    # duoshuo:

# Social
social:
    facebook: Joseph Lingxu Meng
    github: Modrisco
    twitter: MENG_LINGXU
    linkedin: Meng Lingxu
    instagram: joseph.l.meng
    mail: menglingxu95@gmail.com

# Google Analytics
ga:
    id: UA-121813874-1
